set_property IOSTANDARD LVCMOS18 [get_ports CLK]
set_property IOSTANDARD LVCMOS18 [get_ports CS]
set_property IOSTANDARD LVCMOS18 [get_ports DC]
set_property IOSTANDARD LVCMOS18 [get_ports RES]
set_property IOSTANDARD LVCMOS18 [get_ports RST]
set_property IOSTANDARD LVCMOS18 [get_ports EN]
set_property IOSTANDARD LVCMOS18 [get_ports SEL]
set_property IOSTANDARD LVCMOS18 [get_ports SCLK]
set_property IOSTANDARD LVCMOS18 [get_ports SDIN]
set_property IOSTANDARD LVCMOS18 [get_ports VBAT]
set_property IOSTANDARD LVCMOS18 [get_ports VDD]
set_property IOSTANDARD LVCMOS18 [get_ports FIN]
set_property PACKAGE_PIN W5 [get_ports CLK]
set_property PACKAGE_PIN A14 [get_ports CS]
set_property PACKAGE_PIN A16 [get_ports SDIN]
set_property PACKAGE_PIN B16 [get_ports SCLK]
set_property PACKAGE_PIN A15 [get_ports DC]
set_property PACKAGE_PIN A17 [get_ports RES]
set_property PACKAGE_PIN C15 [get_ports VBAT]
set_property PACKAGE_PIN C16 [get_ports VDD]
set_property PACKAGE_PIN U16 [get_ports FIN]
set_property PACKAGE_PIN U18 [get_ports RST]
set_property PACKAGE_PIN W19 [get_ports EN]
set_property PACKAGE_PIN V16[get_ports SEL]

set_property PACKAGE_PIN V16 [get_ports SEL]
